### ISSUE TITLE
Restrictions on Azure subscriptions

### ISSUE THREAD

**Issue by GalOshri** [Microsoft/mwt-ds#13] opened 2016-07-05 18:51 UTC
Based on past conversations, it looks like the deployment will not succeed in all Azure regions. This can depend on the user's subscription (and maybe also the resources in the Decision Service?). We likely need to have a better understanding of this and give additional information in the deployment tutorial, such as which regions have been thoroughly tested.

**Comment by lhoang29** [comment] 2016-07-05 18:59
To clarify: the deployment should be able to succeed in any region **given** that the user's subscription has access to the resources in that region. For example, in one of my subscriptions, I cannot create classic cloud services in West US by default, this is a restriction on the whole account rather than anything related to the DS. The general solution is for the user to open a ticket in Azure portal requesting more access.

**Comment by lhoang29** [comment] 2016-07-05 20:32
Closing per comment above.

**Comment by danmelamed** [comment] 2016-07-05 22:05
I added a "troubleshooting" section on this.

**Comment by slivkins** [comment] 2016-07-07 22:02
So how to look up which regions my subscription has access to? I haven't been able to find it in the Azure portal. Lack of ability to look it up seems like a blocker for successful deployments ...

**Comment by lhoang29** [comment] 2016-07-08 02:01
I added a wiki here: https://github.com/Microsoft/mwt-ds/wiki/Troubleshooting-Guide-and-FAQ-List. There's not an easy way to see a complete list of supported regions that I know of. Rather, you can use the Azure portal UI as trial & error to determine

**Comment by slivkins** [comment] 2016-07-08 02:19
Maybe you specify supported regions when you sign up for the subscription? (then also a good thing to mention in Wiki) Otherwise what, Azure makes everyone play a guessing game??

**Comment by lhoang29** [comment] 2016-07-08 14:21
I don't think so, for my personal subscription I was never asked which subscriptions to use. They might pick the default ones depending on your location.

**Comment by slivkins** [comment] 2016-07-08 14:31
So this another Azure bug that we want them to fix, right?

**Comment by lhoang29** [comment] 2016-07-08 17:17
Am not sure if it's a bug, I just don't know if there's an easy way for someone who's not familiar with Azure to find the list of supported regions in the subscription. I'm only aware of this: https://azure.microsoft.com/en-us/documentation/articles/resource-manager-supported-services/#supported-regions which requires one to use powershell or other APIs to query the regions.

**Comment by slivkins** [comment] 2016-07-08 17:57
It is not that you don't know an easy way -- it is that Azure does not advertise one! And the "solutions" that Azure advertises are really terrible. And it is not for a tricky question like "can I deploy in India", but for which US regions should I use with my US subscription. We really cannot tell users: go install a powershell and learn how to use it and how to interpret the output. So really they would need to try all 5 US locations. Perhaps not a critical issue, but smth that would raise their annoyance level quite a bit. Seems like a bug to me, or at least one of the issues we want to bring up with them ... 

BTW, I assume for each subscription there is a "safe region" where everything works, right?

**Comment by eisber** [comment] 2016-07-08 18:04
Really the issue is that “Deploy to Azure” doesn’t provide a UI implementation for “region” validation for classic compute services. If you try to provision a classic compute service directly in portal it will actually filter/validate the region to my knowledge.

2nd best option is to validate the template correctly, again missing feature.

Markus

**Comment by lhoang29** [comment] 2016-07-12 14:08
closing again according to comments above.

**Closed by lhoang29** 2016-07-12 14:08 UTC

**Comment by danmelamed** [comment] 2016-07-12 15:55
For future reference: moved to Troubleshooting page on the wiki.

**Comment by sidsen** [comment] 2016-07-13 09:44
I don't think we should close this issue, it's proving to be annoying to
users and detrimental to service adoption.

Following up via email.

Sid
