### ISSUE TITLE
Management_Center deployment failure

### ISSUE THREAD

**Issue by JohnLangford** [Microsoft/mwt-ds#35] opened 2016-07-07 21:00 UTC
For 2/6 tests I see a failure to deploy the management_center.  When I look into the audit logs I see the helpful message: "The resource operation completed with terminal provisioning state 'Failed'."  This if for foo-2 and foo-6.

**Comment by lhoang29** [comment] 2016-07-07 21:13
These are same as the last deployment failure you had (also in foo-2) and is a known issue based on our internal thread. The fix will be deployed in Aug time frame.

**Comment by lhoang29** [comment] 2016-07-07 21:14
See #8

**Comment by danmelamed** [comment] 2016-07-17 21:40
duplicate of #8

**Closed by danmelamed** 2016-07-17 21:40 UTC
Labels: duplicate
