### ISSUE TITLE
"reset model" seems to have no effect

### ISSUE THREAD

**Issue by danmelamed** [Microsoft/mwt-ds#12] opened 2016-07-05 17:51 UTC
After entering a bunch of examples in API Test Drive, it says "total learned examples: 44".  Clicking "reset model" and waiting a while, it still says 44.  Clicking a few more examples only increases this number.

**Comment by lhoang29** [comment] 2016-07-05 18:07
duplicate of #6

**Closed by lhoang29** 2016-07-05 18:07 UTC
Labels: bug
