### ISSUE TITLE
Model update time is wrong

### ISSUE THREAD

**Issue by danmelamed** [Microsoft/mwt-ds#23] opened 2016-07-05 20:20 UTC
mc-dmdp2 says 
Latest model obtained at: December 31st 0000, 7:00:00 pm

**Comment by eisber** [comment] 2016-07-05 20:25
duplicate of #7

**Comment by lhoang29** [comment] 2016-07-05 20:29
this should be fixed

**Comment by sidsen** [comment] 2016-07-06 05:41
I just did a deployment and when you first go to the test drive site, the "Last model obtained at" timestamp does appear to be bogus. Perhaps we should put nothing or "None" at the beginning? Also see issue #20, it addresses the refresh rates/consistency of the numbers we print.

**Comment by lhoang29** [comment] 2016-07-06 14:36
should be fixed now in #7

**Closed by lhoang29** 2016-07-06 14:36 UTC
Labels: bug
